# Generated by Django 3.0.3 on 2020-04-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTag',
            fields=[
                ('tag', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_title', models.CharField(default='Blog post', max_length=200, primary_key=True, serialize=False, verbose_name='Title')),
                ('post_desc', models.TextField(max_length=100, verbose_name='Description')),
                ('post_text', models.TextField(verbose_name='Story')),
                ('post_date', models.DateField(verbose_name='Date published')),
                ('post_img', models.ImageField(null=True, upload_to='', verbose_name='Thumbnail')),
                ('post_tag', models.CharField(choices=[('General', 'General'), ('Politics', 'Politics'), ('Entertainment', 'Entertainment'), ('Technology', 'Technology'), ('Business', 'Business')], default='General', max_length=20, verbose_name='Tag')),
                ('featured', models.BooleanField(default=False)),
                ('custom_tag', models.ManyToManyField(to='landingpage.CustomTag')),
            ],
        ),
    ]
