# Generated by Django 3.0.3 on 2020-02-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_blogpost_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='pub_date',
            new_name='Date published',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_text',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_title',
            new_name='Title',
        ),
    ]
