# Generated by Django 3.0.3 on 2020-02-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_auto_20200229_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='Post',
            new_name='post_text',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='Title',
            new_name='post_title',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='Date published',
            new_name='pub_date',
        ),
    ]
