# Generated by Django 3.0.3 on 2020-02-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_auto_20200229_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(verbose_name='Date published'),
        ),
    ]
