# Generated by Django 3.0.3 on 2020-02-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_blogpost_post_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_desc',
            field=models.TextField(max_length=100, verbose_name='Short description'),
        ),
    ]
