# Generated by Django 3.0.3 on 2020-03-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_auto_20200229_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='pub_date',
            new_name='post_date',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='post img'),
        ),
    ]
