# Generated by Django 3.0.3 on 2020-04-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0019_auto_20200331_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='custom_tag',
            field=models.ManyToManyField(to='landingpage.CustomTag'),
        ),
    ]
